# Generated by Django 4.1.7 on 2023-04-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_userip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('All in One Desktops', 'All in One Desktops'), ('Commercial Desktops', 'Commercial Desktops'), ('Gaming PC', 'Gaming PC'), ('Home (Users Notebooks / Laptops)', 'Home (Users Notebooks / Laptops')], max_length=50),
        ),
    ]
