# Generated by Django 4.1.7 on 2023-04-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_request_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='mechanic',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='request',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='request',
            name='mechanic',
        ),
        migrations.AlterField(
            model_name='userip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Mechanic',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
